# Generated by Django 6.0.5 on 2026-05-09 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(max_length=20, unique=True, verbose_name='Mã SV')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ tên')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')], verbose_name='Điện thoại')),
                ('date_of_birth', models.DateField(verbose_name='Ngày sinh')),
                ('gender', models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ')], max_length=10, verbose_name='Giới tính')),
                ('address', models.TextField(blank=True, verbose_name='Địa chỉ')),
                ('class_name', models.CharField(max_length=50, verbose_name='Lớp')),
                ('faculty', models.CharField(max_length=100, verbose_name='Khoa')),
                ('course_year', models.IntegerField(help_text='Năm nhập học', verbose_name='Khóa')),
                ('status', models.CharField(choices=[('studying', 'Đang học'), ('graduated', 'Đã tốt nghiệp'), ('suspended', 'Bị đình chỉ'), ('dropped', 'Đã thôi học')], default='studying', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Sinh viên',
                'verbose_name_plural': 'Sinh viên',
                'db_table': 'students',
                'ordering': ['student_code'],
            },
        ),
    ]
