# Generated by Django 6.0.5 on 2026-05-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20, unique=True, verbose_name='Mã môn')),
                ('course_name', models.CharField(max_length=200, verbose_name='Tên môn')),
                ('credits', models.IntegerField(verbose_name='Số tín chỉ')),
                ('faculty', models.CharField(max_length=100, verbose_name='Khoa')),
                ('semester', models.CharField(choices=[('1', 'Học kỳ 1'), ('2', 'Học kỳ 2'), ('3', 'Học kỳ 3 (Hè)')], max_length=10, verbose_name='Học kỳ')),
                ('academic_year', models.CharField(help_text='VD: 2025-2026', max_length=20, verbose_name='Năm học')),
                ('tuition_fee', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Học phí')),
                ('max_students', models.IntegerField(default=50, verbose_name='Sĩ số tối đa')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Môn học',
                'verbose_name_plural': 'Môn học',
                'db_table': 'courses',
                'ordering': ['course_code'],
            },
        ),
    ]
