# Generated by Django 6.0.5 on 2026-05-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuitionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_credit', models.DecimalField(decimal_places=0, default=500000, max_digits=10, verbose_name='Giá 1 tín chỉ')),
                ('summer_multiplier', models.DecimalField(decimal_places=2, default=1.5, max_digits=4, verbose_name='Hệ số học kỳ hè')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
            ],
            options={
                'verbose_name': 'Cấu hình học phí',
                'verbose_name_plural': 'Cấu hình học phí',
                'db_table': 'tuition_config',
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='tuition_fee',
            field=models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=12, verbose_name='Học phí'),
        ),
    ]
