# Generated by Django 6.0.5 on 2026-05-09 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng ký')),
                ('status', models.CharField(choices=[('registered', 'Đã đăng ký'), ('confirmed', 'Đã xác nhận'), ('cancelled', 'Đã hủy')], default='registered', max_length=20, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='courses.course', verbose_name='Môn học')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='students.student', verbose_name='Sinh viên')),
            ],
            options={
                'verbose_name': 'Đăng ký môn học',
                'verbose_name_plural': 'Đăng ký môn học',
                'db_table': 'registrations',
                'ordering': ['-registered_date'],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
