# Generated by Django 6.0.5 on 2026-05-09 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrations', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TuitionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=20, verbose_name='Học kỳ')),
                ('academic_year', models.CharField(max_length=20, verbose_name='Năm học')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Tổng học phí')),
                ('paid_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Đã đóng')),
                ('remaining_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Còn lại')),
                ('due_date', models.DateField(verbose_name='Hạn đóng')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Tiền mặt'), ('transfer', 'Chuyển khoản'), ('card', 'Thẻ tín dụng')], max_length=20, verbose_name='Hình thức')),
                ('status', models.CharField(choices=[('pending', 'Chưa thanh toán'), ('partial', 'Đã thanh toán một phần'), ('paid', 'Đã thanh toán'), ('overdue', 'Quá hạn')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày đóng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='registrations.registration', verbose_name='Đăng ký')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.student', verbose_name='Sinh viên')),
            ],
            options={
                'verbose_name': 'Học phí',
                'verbose_name_plural': 'Học phí',
                'db_table': 'tuition_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Số tiền')),
                ('payment_method', models.CharField(choices=[('cash', 'Tiền mặt'), ('transfer', 'Chuyển khoản'), ('card', 'Thẻ tín dụng')], max_length=20, verbose_name='Hình thức')),
                ('reference_code', models.CharField(blank=True, max_length=100, verbose_name='Mã tham chiếu')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('paid_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày thu')),
                ('paid_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người thu')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tuition.tuitionpayment', verbose_name='Học phí')),
            ],
            options={
                'verbose_name': 'Lịch sử thanh toán',
                'verbose_name_plural': 'Lịch sử thanh toán',
                'db_table': 'payment_history',
                'ordering': ['-paid_at'],
            },
        ),
    ]
